LiskHQ/lisk-explorer

public/views/delegateMonitor.html
This relates to #4 displaying status and productivity on mobile.
=> Forging status and productivity visible on mobile

README.md
The README was missing a variety of required dependencies and installation instructions were somewhat vague. This PR resolves both of these issues and includes instructions on using the test-suite as well.
=> Improve README.md instructions

public/src/css/activityGraph.css, public/src/css/common.css, public/src/css/delegateMonitor.css, public/src/css/marketWatcher.css, public/src/css/networkMonitor.css
Closes https://github.com/LiskHQ/lisk-explorer/issues/64
=> Adjust theme to match lisk.io

public/src/css/common.css, public/views/address.html
This improvement pack makes address.html more streamlined while retaining all data fields. This should close issue #58 
Here we can see the changes viewed from Web browser:
Here is a view of the mobile:
=> More address.html improvements

known.json, public/views/address.html
Closes https://github.com/LiskHQ/lisk-explorer/issues/76
=> Fix for loading genesis account, added as known address

app.js, config.global.js, config.js, package.json, sql/index.js, test/config.test, utils/database.js, utils/index.js
Closes https://github.com/LiskHQ/lisk-explorer/issues/73
=> Initial support for postgres

public/index.html, public/src/js/config.js, public/src/js/directives/breadCrumb.js, public/views/index/breadCrumb.html
=> Improve navigation - Fixes #51

LICENSE, README.md, package.json
=> Changing license from MIT to GPLv3 - Closes #117

public/src/js/config.js, public/src/js/controllers/delegate.js, public/src/js/directives/breadCrumb.js
=> Add address to breadcrumbs, fixes #111

public/src/js/filters.js, public/views/address.html, public/views/delegate.html, public/views/delegateMonitor.html, public/views/networkMonitor.html, public/views/transaction.html
Closes https://github.com/LiskHQ/lisk-explorer/issues/122 https://github.com/LiskHQ/lisk-explorer/issues/123 https://github.com/LiskHQ/lisk-explorer/issues/125 https://github.com/LiskHQ/lisk-explorer/issues/126 https://github.com/LiskHQ/lisk-explorer/issues/129 https://github.com/LiskHQ/lisk-explorer/issues/130 https://github.com/LiskHQ/lisk-explorer/issues/132
=> Minor fixes after router change

public/views/index/header.html
Closes https://github.com/LiskHQ/lisk-explorer/issues/124
=> Fix currency switcher

.github/issue_template.md
=> Creating issue template - Closes #170

src/components/delegate-monitor/delegate-monitor.html
=> Make active / standby tabs in Delegate monitor page visible again

src/components/delegate-monitor/delegate-monitor.html
=> Fix the issue in progress bar caused by upgrading bootstrap

src/components/network-monitor/network-monitor.html
=> Fix the issue in tabs in network monitor caused by upgrading bootstrap

src/components/address/address.html, src/components/delegate/delegate.html, src/shared/index.js, src/shared/votes/index.js, src/shared/votes/votes.directive.js, src/shared/votes/votes.html
=> Add votes list for non-delegate addresses

src/components/delegate/delegate.html
Revert mistakenly committed template in delegate page. Closes #181
=> Add delegate rank/status to delegate page

Gruntfile.js, config.json, lib/candles/abstract.js, lib/candles/bittrex.js, lib/candles/poloniex.js, package.json, tasks/candles.js, test/api/candles.js, test/config.json, test/config_lisk.json
- Backport https://github.com/LiskHQ/lisk-explorer/pull/185
- Increase timeout for tests
=> Backport #185

src/components/delegate-monitor/delegate-monitor.html
=> Fix the usage of natural filter function from rootScope

README.md, package.json, src/components/address/address.html, src/components/delegate-monitor/delegate-monitor.html, src/components/delegate-monitor/delegate-monitor.service.js, src/components/delegate/delegate.html, src/components/network-monitor/network-monitor.html, src/filters/time-span.js, src/shared/index.js, src/shared/votes/index.js, src/shared/votes/votes.directive.js, src/shared/votes/votes.html
- Update webpack config file to have the application running on a unique port (6040).
- Update Readme to reflex changes in v
1.2.0
Closes #166
=> Update webpack and readme - Closes #166

config.js, test/config.test, utils/exchange-api/index.js
=> Add rub exchange

package.json, webpack.config.js
=> Fix runtime error on production build - Fixes #177

src/components/network-monitor/network-monitor.html, src/components/network-monitor/network-monitor.service.js
- Use includes instead of contains.
- Fix the typo in network monitor template.
Closes #197
=> Network monitor page fixings - Closes #197

package.json, src/components/network-monitor/network-monitor.service.js
=> Fix OS markers in network monitor

src/assets/styles/common.css, src/components/activity-graph/activity-graph.html, src/components/address/address.html, src/components/blocks/block.html, src/components/blocks/blocks.html, src/components/delegate-monitor/delegate-monitor.html, src/components/delegate/delegate.html, src/components/footer/footer.html, src/components/home/home.html, src/components/network-monitor/network-monitor.html, src/components/top-accounts/top-accounts.html, src/components/transactions/transactions.html, src/filters/currency.js, src/shared/transaction-item/transaction-item.html
=> Beautify amounts - Closes #144

src/assets/styles/common.css, src/components/activity-graph/activity-graph.html, src/components/address/address.html, src/components/blocks/block.html, src/components/blocks/blocks.html, src/components/delegate-monitor/delegate-monitor.html, src/components/delegate/delegate.html, src/components/footer/footer.html, src/components/home/home.html, src/components/network-monitor/network-monitor.html, src/components/top-accounts/top-accounts.html, src/components/transactions/transactions.html, src/filters/currency.js, src/shared/transaction-item/transaction-item.html
Display Vote weight on delegate page
=> Add vote weight to delegates page

src/assets/styles/common.css, src/components/header/header.directive.js, src/components/header/header.html
I found that I made a mistake in this PR https://github.com/LiskHQ/lisk-explorer/pull/156.
This PR fixes the URL path to logo image.
=> Fix css for retina display

lib/candles/abstract.js
Closes https://github.com/LiskHQ/lisk-explorer/issues/209
=> Reset duration prior to start update on candles - Closes #209

api/accounts.js, benchmarks/accounts.js, lib/api/accounts.js, lib/api/common.js, test/api/accounts.js
=> Allow search by public key - Closes #41

src/components/address/address.html
=> Display votes on address page if account is delegate - Closes #221

src/shared/votes/votes.html
=> Fix missing votes count - Closes #219

src/components/address/address.html, src/components/delegate/delegate.html
=> Fix missing delegate proposals icons - Closes #217

src/components/blocks/block.html
=> Transactions are not displayed on blocks pages - Closes #215

src/components/search/search.html
=> Fix seach placeholder formatting - Closes #213

src/components/header/header.html
=> Fix menu on mobile - Closes #211

app.js, utils/logger.js
Closes https://github.com/LiskHQ/lisk-explorer/issues/240
=> Fix jshint errors - Closes #240

package.json
https://github.com/LiskHQ/lisk-explorer/issues/238
=> Fix missing comma - Closes #238

src/components/delegate-monitor/delegate-monitor.service.js
=> Wrong best forger - Closes #244

config.js
Adds a minor comment for ports and fixes default logging location.
=> Default logs to write to logs folder - Closes #248

src/components/address/address.component.js, src/components/address/address.html
=> Improve the error message for transactions filter - Closes #251

lib/api/transactions.js, src/components/address/address.component.js
- In Client: If neither of senderId or recipientId are defined, we set the page address Id to both.
- In Api: If the senderId and RecipientId are the same, we'll make 2 Api calls and merge the results.
Closes #254
=> Default values for search - Closes #254

.eslintrc, Gruntfile.js, Jenkinsfile, package.json, utils/candles.js, utils/exchange-api/index.js, utils/exchange.js, utils/knownAddresses.js, utils/logger.js, utils/orders.js
Temporarily sets eslint to only run in utils directory. Then applies eslint rules.
Closes #265
=> Eslint fixings in utils directory- Closes #265

.eslintrc, benchmark.js, benchmarks/accounts.js, benchmarks/blocks.js, benchmarks/common.js, benchmarks/delegates.js, benchmarks/index.js, benchmarks/statistics.js, benchmarks/transactions.js, package.json
Temporarily sets eslint to only run in benchmarks directory. Then applies eslint rules.
Closes #268
=> Eslint fixings in benchmarks directory - Closes #268

.eslintrc, api/accounts.js, api/blocks.js, api/common.js, api/delegates.js, api/exchanges.js, api/index.js, api/statistics.js, api/transactions.js, package.json
Temporarily sets eslint to only run in Api directory. Then applies eslint rules.
Closes #266
=> Eslint fixings in Api directory - Closes #266

sockets/activityGraph.js, sockets/delegateMonitor.js, sockets/header.js, sockets/index.js, sockets/marketWatcher.js, sockets/networkMonitor.js, src/components/header/header.service.js, src/components/market-watcher/market-watcher.service.js, src/components/network-monitor/network-monitor.service.js
Temporarily sets eslint to only run in  `sockets` and `src/components` directory. Then applies eslint rules.
Closes #273
=> Eslint fixings in sockets directory - Closes #273

.eslintrc, app.js, config.global.js, config.js, features/step_definitions/generic.step.js, features/support/util.js, karma.conf.js, package.json, protractor.conf.js, tasks/candles.js, test/api/accounts.js, test/api/blocks.js, test/api/common.js, test/api/delegates.js, test/api/exchanges.js, test/api/statistics.js, test/api/transactions.js, test/node.js
Temporarily sets eslint to only run in all remaining files. Then applies eslint rules.
Closes #279
=> Eslint fixings in all remaining files directory - Closes #279

known.json
=> Add account name in known.json

Gruntfile.js, api/accounts.js, api/blocks.js, api/common.js, api/delegates.js, api/exchanges.js, api/handler.js, api/index.js, api/statistics.js, api/transactions.js, benchmarks/accounts.js, benchmarks/blocks.js, benchmarks/common.js, benchmarks/delegates.js, benchmarks/handler.js, benchmarks/index.js, benchmarks/statistics.js, benchmarks/transactions.js, lib/api/accounts.js
=> Refactor repeated codes in Api - Closes #281

app.js, config.js, lib/api/accounts.js, test/api/accounts.js, utils/knownAddresses.js
- Updates the Lisk core URLs used in Explorer
- Adapts tests accordingly
- Applies some code cleanups
Closes #287
=> Update Api/accounts endpoints - Closes #287

app.js, lib/api/transactions.js, test/api/transactions.js
=> Update Api/transactions endpoints - Closes #291

lib/api/blocks.js, test/api/blocks.js
=> Update Api/blocks endpoints - Closes #290

app.js, lib/api/statistics.js, src/shared/peers/peers.html, test/api/statistics.js
=> Update Api/statistics endpoints - Closes #290

test/api/common.js
=> Update Api/search endpoints - Closes #303, #304

lib/api/blocks.js, lib/api/delegates.js, lib/api/statistics.js, sockets/delegateMonitor.js, sockets/header.js, src/components/header/header.service.js, src/components/network-monitor/network-monitor.service.js, test/api/blocks.js, test/api/common.js, test/api/delegates.js, test/api/exchanges.js
- Updates the Lisk core Api usages in sockets.
- Updates the remaining Lisk core Api usages in Explore APIs.
- Minor updates in client app to adapt the changes introduced in responses.
- Removes everything related to Delegate Proposals.
Closes #306
=> Fix the regressions introduced after the migration - Closes #306

src/components/network-monitor/network-monitor.service.js, src/index.ejs
- Checks if the version has a character in the end, the takes the character into account.
- Removes hard coded bundle scripts since the webpack plugin adds them.
Closes #322
=> Hot fix version.sort method - Closes #322

known.json
=> Add Coincheck and Iconomi to known addresses - Closes #330

src/components/network-monitor/network-monitor.service.js
=> Improvements in custom sort function - Closes #335

src/components/network-monitor/network-monitor.service.js
- Fixes the issue that caused to sometimes show best heights in wrong order.
- Uses JS syntax to check the type of variables
Closes #333
=> Fix best height - Closes  #333

Jenkinsfile, features/step_definitions/generic.step.js, test/config.test
It needs a little tidying up (especially that line where I start explorer and I'm specifying the redis port twice), but so far, it "works on my box"
Closes #300
=> changes to enable concurrent runs - Close #300

README.md, package.json
=> Bump version 1.3.2

known.json
=> Add changelly to known addresses - Closes #341

.github/pull_request_template.md
We need to have a pull request template to ensure minimum required information for ease of review.
I've created the template based on @ginacontrino and @slaweet 's suggestion.
check `.github/pull_request_template.md` 
- The PR solves #351 
=> Create Pull request template - Closes #351

src/components/network-monitor/network-monitor.service.js, src/services/tx-types.js
We had a wrong set of transaction type codes
I changed them based on [Lisk protocol documentation](https://docs.lisk.io/docs/the-lisk-protocol-transactions)
I've also included a minor fixing in the iteration of network monitor heights counters.
See the changed files
- The PR solves #353 
=> Fix transaction types - Closes #353

protractor.conf.js, src/assets/styles/common.css, src/components/header/header.css, src/components/header/header.directive.js, src/components/header/header.html, src/components/search/search.html
**What was the problem?**
Network statistics uses small font and is compressed in a small space which make it hard to read.
**What did I fixed?**
My suggestion is to move this part of header to a separated row under the current header:
Then we can use bigger font size and some padding to improve readability.
Make sure:
- Resolves #349 
- Doesn't break in smaller screens
=> Improve network statistics readability - Closes #349

README.md, package.json
=> Bumping version 1.4.0 - Closes #355

README.md, package.json
Bumping version 1.4.1
Closes #364
=> Bumping version 1.4.1 - Closes #364

.gitignore, features/menu.feature, lib/api/common.js, lib/api/delegates.js, package.json, src/components/header/header.css, src/components/header/header.html, src/components/market-watcher/market-watcher.service.js, src/components/search/search.directive.js, src/components/search/search.html, test/api/common.js, test/api/delegates.js
Explained clearly in #371 
**In Node Api:**
I've removed the limitation of the results coming from Lisk-core, then used [string-similarity](https://www.npmjs.com/package/string-similarity) to sort the results based on the similarity of the username to the given query parameter. 
This leaves us with the most similar - probably the direct result - to the search query.
at the end I changed the structure of the results coming from this endpoint.
**In Angular App:**
I've created a suggestion list and prevented automatic redirection to address page.
Test for a random username fully and partially to see the results.
- The PR solves #371 
- All new code is covered with tests
=> Tweak search results - Closes #371

src/components/market-watcher/market-watcher.service.js
=> Linting fix - Closes #385

known.json
=> Add HitBTC Hot Wallet to the known wallets list - Closes #370

known.json
=> Add Bitbay and Binance to the known wallets list - Closes #369

known.json
=> Add new wallet of Coincheck.com - Closes #404

src/components/footer/footer.html, src/components/header/header.html
=> Header and footer updates - Closes #406

README.md, e2e-test-setup.sh
=> README update - Closes #407

package.json, robots.txt
=> Add robots.txt - Closes #444

lib/orders/bittrex.js
The process could run into an unhandled exception.
I've added additional check which proves if a given object contains the right field.
The problem itself occurred very rarely before. The best way is to wait until The Bittrex API provides wrong data.
- The PR solves #450
=> Data parsing error fix - Closes #450

lib/candles/abstract.js
Wrong data incoming from external REST service could cause a process crash by raising an exception.
I've added additional data type checks and fixed one bug I've noticed during a review.
We need to observe the process on the testnet server.
- The PR solves #457 
=> Market Watcher validation error - Closes #457 

lib/api/common.js
Getting "No matching records found!" when searching for valid transaction
I've updated the attribute name returned by the request
Search for a valid transaction. You should be redirected to the transaction page.
- The PR solves #464
=> Fix search by transaction - Closes #464

.gitignore, app.js, config.js, e2e-test-setup.sh, lib/api/blocks.js, lib/api/transactions.js, test/api/accounts.js, test/api/blocks.js, test/api/common.js, test/api/delegates.js, test/api/exchanges.js, test/api/statistics.js, test/api/transactions.js
This small fix updates Lisk Core API request in delegate websocket implementation.
- The PR solves #403
=> Update delegate monitor - Closes #403

.gitignore, app.js, config.js, e2e-test-setup.sh, lib/api/blocks.js, lib/api/transactions.js, test/api/accounts.js, test/api/blocks.js, test/api/common.js, test/api/delegates.js, test/api/exchanges.js, test/api/statistics.js, test/api/transactions.js
=> API update transactions - Closes #398

lib/candles/abstract.js
The application crashed while receiving data from Bittrex for the Market Watcher.
The function responsible for filling gaps in the chart did not check input data against an undefined and empty array.
I've put additional checks to make sure that data are correct.
Run market watcher candle rebuild, then a process and wait for a response from Bittrex that does not contain any data.
- The PR solves #475 
=> Fix for Market Watcher stability bug - Closes #475

Jenkinsfile, src/components/network-monitor/network-monitor.html
We had a problem displaying disconnected peers. as a result of [this](https://github.com/LiskHQ/lisk-explorer/issues/417) conversation, we decided to remove the list of disconnected peers.
Removed disconnected peers.
Make sure there's only a list of connected peers In network monitor.
- The PR solves #417 
=> Remove disconnected peers - Closes #417

lib/api/delegates.js, sockets/delegateMonitor.js
Some columns in the `Delegate monitor` were missing or displayed inaccurate data.
Appropriate fixes where applied to make the data consistent.
The most important was the API result that caused missing blocks array in the response.
Also, the limit of forgers was set to 100 which resulted in one forger data missing.
Check the `Delegate monitor` table in order to make sure that the data are consistent. 
- The PR solves #526
=> Delegate data missing - Closes #526

lib/api/accounts.js, lib/api/blocks.js, lib/api/delegates.js, lib/api/statistics.js
The application crashed randomly when the response was undefined.
The solution checks if there is an undefined or null and returns an empty object to prevent the application from crashing.
Run the app on testnet, it should not break.
- The PR solves #523
=> Mapping stability fix - Closes #523

src/filters/net-hash.js
=> Support for the betanet nethash

test/api/accounts.js
Voters and Votes endpoints didn't have proper test coverage.
Tests were added accordingly.
run `npm test`
- The PR solves #470
=> Add test for voters - Closes #470

app.js
The Explorer process was doing an unsuccessful attempt to connect when the 1.0-compatible version was used against Core 0.9 -> the process crashed instantly.
There is an additional check before the server API is initialized.
Any problems with connecting the client to the right version of the core node will cause a proper shutdown and a message in logs.
Run the app against a 0.9 node, the process will be stopped gracefully.
- The PR solves #516
=> The Explorer checks node version before start - Closes #516

src/assets/styles/common.css, src/components/blocks/blocks.html, src/components/header/header.css, src/components/header/header.html, src/components/home/home.html, src/components/market-watcher/market-watcher.css, src/components/network-monitor/network-monitor.html, src/components/search/search.directive.js, src/components/search/search.html, src/components/top-accounts/top-accounts.html, src/shared/transaction-item/transaction-item.html, src/shared/transactions-list/transactions-list.html
There's a list of issues explained in #536. 
- The PR solves #536 
=> Fine tuning and improvements in UI - Closes #536

Jenkinsfile, app.js, config.global.js, config.js, lib/api/accounts.js, lib/api/delegates.js, utils/knownAddresses.js
Voters List on delegate page wasn't showing username when it was a delegate or known address
As this list can be very big, I've implemented a caching for saving known accounts information and avoid to make core calls repeatedly.
Access `/delegate/537318935439898807L`
You should see **gottavoteemall** as voter
- The PR solves #550 and #521 
=> Voters list not displaying known username - Closes #550

api/handler.js, config.js, lib/api/accounts.js, package.json, utils/core.js, utils/http.js
Some HTTP requests were not handled properly. There is a lot of copy-paste code in the part responsible for communication with Lisk Core
The HTTP and Core abstraction layers were created.
Run the application, tests should be passing.
- The PR solves #565
=> Add abstraction layer for generic HTTP and Lisk Core requests - Closes #565

src/components/delegate-monitor/delegate-monitor.html, src/components/network-monitor/network-monitor.service.js, src/services/order-by.js, src/shared/peers/peers.html
The sorting functionality didn't work properly.
It was solved for the branch 1.6.0, in the issue #449.
This PR integrates that change with 2.0.0.
Run network monitor and check the sorting behavior.
- The PR solves #560
=> Network Monitor table sorting update - Closes #560

lib/orders/abstract.js, lib/orders/bittrex.js, utils/exchange-api/index.js
There are random errors during Market Watcher updates that lead to process crashes.
Additional validation logic has been added to the parts of the code that depends on 3rd party services.
The app should be stable on devnet/testnet/betanet.
- The PR solves #545
=> Market Watcher stability fix - Closes #545

src/assets/styles/common.css, src/components/top-accounts/top-accounts.component.js, src/components/top-accounts/top-accounts.html, src/services/less-more.js
If the Api call didn't return data, the UI gets stuck in loading state.
I've added a message to properly notify the user about the situation.
- The PR solves one the problems in #537
=> Add no result state template to top accounts - Subtask #537 

src/shared/transactions-list/transactions-list.html
=> Sorting issue fix - Closes #579

Jenkinsfile
Jenkinsfile lacked slack integration
I added it
Conveniently by pushing this branch to github (and doing a few replay builds to force the error condition)
- The PR solves #583 
=> Update Jenkinsfile to implement slack notifications

lib/api/blocks.js
=> Changed networkHeight to height - Solves #619

lib/api/transactions.js, src/filters/tx-recipient.js, src/filters/tx-sender.js, test/api/transactions.js, utils/knownAddresses.js
Bad performance across the application.
I've improved the processTransaction function and removed some unnecessary steps.
Access an address page with big number of transactions
- The PR solves #474
=> Bad performance - Closes #474

src/components/bread-crumb/bread-crumb.css
=> Breadcrumb style update - Closes #641

src/assets/styles/common.css, src/components/address/address.html
Non matching styling on secondary navbar of the Address page
Used the same style for both informations
Access any Address page and scroll down
- The PR solves #647 
=> Matching Address and Final Balance styling - Closes #647

src/components/header/header.html
=> Make labels bold on network status bar - Closes #638

src/assets/styles/tableMobile.css
=> Reduce space between lines on mobile view of transactions table - Closes #643

src/assets/styles/common.css, src/components/blocks/blocks.html
=> Apply new button style - Closes #644

features/address.feature, features/block.feature, features/delegate.feature, features/transaction.feature, src/app/states.js, src/components/bread-crumb/bread-crumb.directive.js
=> Add current page to the breadcrumb bar - Closes #640

features/footer.feature, src/components/footer/footer.html
=> Update decimal places options - Closes #648

src/assets/styles/common.css, src/components/address/address.html, src/components/header/header.css, src/components/search/search.directive.js, src/components/search/search.html, src/directives/clip-copy.js, src/shared/transaction-item/transaction-item.html
=> Add changes from 1.6.1 - Closes #508

src/assets/styles/common.css
=> Show the whole footer when page doesn't scroll - Closes #688

src/assets/styles/common.css, src/components/blocks/blocks.html, src/components/delegate-monitor/delegate-monitor.html, src/components/home/home.html, src/components/top-accounts/top-accounts.html, src/index.ejs, src/shared/transactions-list/transactions-list.html
=> Update buttons to match Lisk look and feel - Closes #683

Jenkinsfile, test/data/config.json
`e2e-test-setup.sh` wasn't able to start local core instance
Updated the `test/data/config.json` required to execute `e2e-test-setup.sh`
`bash ./e2e-test-setup.sh /PATH_TO_LISK_DIR`
- The PR solves #717  
=> Update core test config file - Closes #717

features/address.feature, features/block.feature, features/delegateMonitor.feature
Inconsistence on core responding for transactions with `limit` and `offset`
The issue was fixed on core 1.0.0-beta.9 and I just updated the tests
`npm run e2e-test -s`
- The PR solves #556 
=> Update e2e tests due core fix - Closes #556

src/components/bread-crumb/bread-crumb.css
=> Add margin-top to breadcrumb bar - Closes #718

config.js, features/menu.feature, test/config.test, utils/exchange-api/index.js
=> Add Japanese Yen (JPY) price ticker - Closes #730

config.js, features/menu.feature, test/config.test, utils/exchange-api/index.js
=> Add Polish Zloty (PLN) price ticker - Closes #728

config.js, features/menu.feature, test/config.test, utils/exchange-api/index.js
=> Add British Pound (GBP) price ticker - Closes #729

features/delegateMonitor.feature, features/transaction.feature, src/components/transactions/transactions.html
Wrong attribute from delegate object
Used the correct attribute and added e2e tests
`npm run e2e-test`
- The PR solves #723
=> Fix voting transaction link - Closes #723

Jenkinsfile
Jenkinsfile was using functions shared across projects that can be imported now from https://github.com/LiskHQ/lisk-jenkins
Remove functions and add import
Tested in Jenkins
=> Use shared library

src/components/network-monitor/network-monitor.css, src/shared/peers/peers.html
=> Medium viewport peers table fix - Closes #742

src/components/transactions/transactions.html
=> Data field regression - Closes #745

lib/api/accounts.js, lib/api/blocks.js, lib/api/delegates.js, lib/api/statistics.js, lib/api/transactions.js, test/api/accounts.js, test/api/blocks.js, test/api/delegates.js, test/api/exchanges.js, test/api/statistics.js, test/api/transactions.js
=> Review types provided by the Explorer 2.x API - Closes #706

config.js, features/menu.feature, src/app/app.js, src/assets/styles/common.css, src/components/currency-selector/currency-selector.directive.js, src/components/currency-selector/currency-selector.html, src/components/header/header.html, src/components/navigation-dropdown/index.js, src/components/navigation-dropdown/navigation-dropdown.directive.js, src/components/navigation-dropdown/navigation-dropdown.html, src/components/navigation-dropdown/navigation-dropdown.module.js, src/components/rounding-selector/index.js, src/components/rounding-selector/rounding-selector.directive.js, src/components/rounding-selector/rounding-selector.html, src/components/rounding-selector/rounding-selector.module.js, src/filters/currency-code-to-name.js, src/filters/index.js, test/config.test, utils/exchange-api/index.js
* The PR solves #738
* Tests pass
=> Merge changes from 1.7 to 2.1 - Closes #738

lib/api/blocks.js
* The PR solves #760 
* Tests pass
=> Check delegate present before parsing - Closes #760

test/api/common.js, test/api/exchanges.js, test/api/statistics.js, test/api/transactions.js
* The PR solves #754 
* Tests pass
=> Unskip exchanges tests and price ticker test - Closes #754

features/aCookieBanner.feature, package-lock.json, package.json, src/app/app.js, src/assets/styles/common.css, src/components/cookies-banner/cookies-banner.directive.js, src/components/cookies-banner/cookies-banner.html, src/components/cookies-banner/cookies-banner.module.js, src/components/cookies-banner/index.js, src/index.ejs
* The PR solves #750
* Tests pass
=> Add cookies banner - Closes #750

app.js, src/index.ejs
* The PR solves #751
* Tests pass
=> Add Google Tag Manager for Analytics - Closes #751

app.js
* The PR solves #781 
* Tests pass
=> Merge fix from 1.x to 2.x - Closes #781

services/newsfeed/TwitterService.js
* The PR solves #789 
* Tests pass
=> Add safety check during Twitter response URL parse - Closes #789

src/assets/styles/common.css
* The PR solves #798 
* Tests pass
=> Make cookies banner always visible - Closes #798

src/components/search/search.directive.js, src/components/search/search.html
* The PR solves #785 
* Tests pass
=> Make search icon perform the search - Closes #785

lib/api/transactions.js, src/components/address/address.component.js, src/services/less-more.js
Advanced search wasn't properly migrated to work with core 1.0
I've updated the params name and logic
Try different combinations of search on transactions list for a particular address
* The PR solves #758
* Tests pass
=>  Fix transactions advanced search - Closes #758

README.md
* The PR solves #784
* Tests pass
=> Update README.md - Closes #784

Jenkinsfile, config.js, src/app/run.js
The Service URL can be set by the config file. This solution has a few drawbacks: it makes hard to change http to https and also needs a rebuild of the frontend code every time the API path is changed.
Till now I've changed the config file structure to accept the URL more consistent way.
Rebuild is still needed to be done on each URL change, there is an appropriate information in the config file.
The Jenkinsfile was updated to skip E2E tests.
Configure & run the app against the testnet node.
* The PR solves #792
* Tests pass
=> Config file takes URL as a param

package-lock.json, package.json
* The PR solves #832
* Tests pass
=> Merge code from v2.1.8 - Closes #832

src/assets/styles/common.css, src/components/footer/footer.html
- Because the font awesome's version was 4, some social icons were not updated.
- Added social icons, as they are aligned with the ones at lisk.io.
- confirmed the display on a browser and checked the link.
* The PR solves #848 
* Tests pass
=> Footer Icons Updates - Closes #848

src/assets/styles/common.css, src/components/network-monitor/network-monitor.html
The column widths of the top parts were not aligned.
Set all the column width for 'col-sm-' to 6.
Adjusted the font size and weight for the block accordingly.
Checked on the browser.
* Tests pass
=> UI update for Network Monitor page - #859

src/assets/styles/common.css, src/assets/styles/tableMobile.css
There was too much space in between H1 and container, 
Modified the padding value of h1.
Checked on a browser.
* Tests pass
=> Modifiy the padding-bottom for h1 - Closes #859

lib/api/transactions.js, src/app/states.js, src/assets/styles/common.css, src/components/address/address.html, src/components/transactions/transactions.component.js, src/components/transactions/transactions.html, src/services/pagination.js, src/shared/transactions-filter/transactions-filter.directive.js, src/shared/transactions-filter/transactions-filter.html, src/shared/transactions-list/transactions-list.html, utils/knownAddresses.js
Filtering could not be set by URL which makes sharing links difficult.
The transaction page respects the URL parameters and applies it to filters.
Open transaction browser.
* The PR solves #814 #819 #773 #812 
* Tests pass
=> URL-based filters - Closes #814

src/assets/styles/common.css, src/components/home/home.component.js, src/components/home/home.html
The redesigned home page was not working properly.
The main design was changed and adapted to the new frontend logic.
Run the application in the browser.
* The PR solves #859
* Tests pass
=> Home page redesign - Closes #859

src/assets/styles/common.css, src/components/delegate-monitor/delegate-monitor.html
- The height of the child elements in the top section at Delegate Monitor were not consistent, and it sometimes caused wrong collapse of some elements.
- Applied flex and flex-wrap in the parent container, and made the height of all the child elements same.
- Refactored the template code accordingly.
- Checked on the browser.
* Tests pass
=> Fix grid of top section of Delegate Monitor - Closes #859

Jenkinsfile, package.json
This branch is created to check the Jenkinsfile compatibility.
* Tests pass
=> Npm scipts

features/delegate.feature, src/components/delegate/delegate.component.js, src/components/delegate/delegate.html
The delegate page was broken.
The component - template and logic are rewritten.
Go to the delegate page.
Run e2e tests.
* The PR solves #905 
* Tests pass
=> Fix the delegate page - Closes #905

package-lock.json, package.json
Dependencies were outdated and compromised the security of the app.
`npm audit fix`
`npm run test` && `npm run test:e2e`
* The PR solves #906
* Tests pass
=> Update dependencies - Closes #906

app.js, lib/api/statistics.js, lib/candles/abstract.js, lib/candles/bittrex.js, lib/orders/abstract.js, lib/orders/bittrex.js, package-lock.json, package.json, sockets/delegateMonitor.js, sockets/header.js, sockets/networkMonitor.js, src/components/network-monitor/network-monitor.html, src/components/network-monitor/network-monitor.service.js, utils/candles.js, utils/exchange-api/index.js, utils/orders.js, utils/socketClient.js
Explorer was unstable when connected to Core 2.0
- Network Monitor WebSocket implementation was updated
- data are fetched during start and updated in regular intervals independently from a user activity
- updates to geolocation logic -> data are loaded in parallel
- Delegate Monitor WebSocket implementation was updated
- data are fetched during start and updated in regular intervals independently from a user activity
- data are refreshed after a block is built or a round is changed
- Frontend bug for statistics was eliminated
Check the delegate and network pages in the UI
* The PR solves #915
* Tests pass
[commit …
=> Delegate monitor update - Closes #915

src/components/footer/footer.html, src/components/network-monitor/network-monitor.html
**What was the problem?**
There was redundant usage of the word "within" under the Statistics tab in the Network Monitor, "Number of blocks with transactions within within the last ...."
**How did I fix it?**
Went to where the problem is located, src/components/network-monitor/network-monitor.html and made the proposed change of removing the repeated word.
Correcting it to "Number of blocks with transactions within the last ... "
**How to test it?**
Go to Network Monitor on the Explorer and check the Statistics tab "Number of Blocks with transactions within within the last ..." 
**What was the problem?**
We consolidated chat platforms to Discord and yet Gitter.IM and RocketChat logos remain in the footer of the official explorer.
**How did I fix it?**
Went to where the problem is located, …
=> Updates to Network Monitor and Footer

features/footer.feature, src/components/footer/footer.html
https://github.com/LiskHQ/lisk-explorer/issues/924#issuecomment-551485900
I implemented 2. and 3. from https://github.com/LiskHQ/lisk-explorer/issues/924#issuecomment-552342354 as agreed by @MichalTuleja 
1. Open Explorer
1. Scroll to the bottom and check the links
* The PR resolves #924
* Tests pass
=> Update footer social links - Closes #924

app.js, lib/api/blocks.js, package-lock.json, package.json, src/components/home/home.html, src/components/transactions/transaction.html, src/filters/epoch-stamp.js, src/filters/net-hash.js, src/filters/time-stamp.js, src/filters/tx-recipient.js, src/services/tx-types.js, src/shared/transaction-item/transaction-item.html
The UI part was missing support for the new transaction types.
- Added exceptions for type 8
- Added mapping for all new transaction types
`npm test` + manual UI testing
* The PR solves #937
* Tests pass
=> Update UI to support transaction types 8-15 - Closes #937
