LiskHQ/lisk-explorer

- api/delegates.js
- app.js
- lib/api/delegates.js
- lib/api/transactions.js
- public/src/css/common.css
- public/src/js/controllers/delegateMonitor.js
- public/src/js/filters.js
- public/src/js/services/delegateMonitor.js
- public/src/js/services/header.js
- public/views/address.html
- public/views/delegateMonitor.html
- public/views/index/header.html
- public/views/networkMonitor.html
- sockets/header.js
Added links to delegate proposals in delegate monitor (closes https://github.com/LiskHQ/lisk-explorer/issues/36):
- added `/api/delegates/getDelegateProposals` endpoint
- added links to delegate proposals in delegate monitor (for active and
standby delegates)
- added link to delegate proposal on address page
Other changes:
- removed bad-looking underline decoration on links (hover, focus)
- removed target="_new" in various places
- dispaly public key on address page (closes https://github.com/LiskHQ/lisk-explorer/issues/26)
- added security headers: X-Frame-Options, X-Content-Type-Options, X-XSS-Protection, Content-Security-Policy (closes https://github.com/LiskHQ/lisk-explorer/issues/13, closes https://github.com/LiskHQ/lisk-explorer/issues/15)
> Improvment pack

- known.json
To improve visibility of the community fund we should add this to the known.json.
Closes issues #82
> Add community fund to known.json - Closes #82

- public/views/address.html
In response to #86 this hides the respective full and mobile versions of the public key display field when they are unknown.
Closes https://github.com/LiskHQ/lisk-explorer/issues/86 //Mq
> Hide Public key field if not present

- public/src/css/no-more-tables.css
- public/src/css/table-mobile.css
- public/views/transaction.html
- public/views/transaction/list.html
- public/views/transaction/tx.html
Have transactions for an account be formatted as a table instead of the blocks.  After seeing it, I prefer this look, but it's more of a change than the other PR.
I still have an inline style, but I didn't want to change too many files at once since I only briefly tested this in one browser on one computer.
Wasn't sure about keeping the slightly rounded corners on the amount boxes too
> Switching tx's to table view

- lib/api/candles.js
- lib/api/orders.js
- public/src/js/services/delegateMonitor.js
- public/src/js/services/forgingMonitor.js
- public/src/js/services/forgingStatus.js
- sockets/delegateMonitor.js
- sql/delegates.js
- sql/index.js
Improved delegate monitor:
- using SQL query to acquire active delegates blocks
- improve forging statuses handling when delegate not forged a block yet
Closes https://github.com/LiskHQ/lisk-explorer/issues/30
> Make delegate monitor forks prone - Closes #30

- public/views/delegate.html
add a new row stating the address to whom this delegate belongs, anchored to the corresponding address page
> State corresponding address on delegate page, fixes 112

- src/assets/styles/common.css
- src/components/bread-crumb/bread-crumb.directive.js
- Add possibility to set breadcrumb parameters using the callback of any sync function
- Fix typos
- Unify the spaces on both sides of the separators
Closes #127
Closes #141
> Breadcrumb fixings - Closes #127 and #141

- Gruntfile.js
- config.global.js
- config.js
- lib/candles/abstract.js
- lib/candles/bittrex.js
- lib/candles/poloniex.js
- tasks/candles.js
- test/api/exchanges.js
- test/config.test
- test/config_lisk.json
- Update `config.json` for Lisk
- Skip exchange if not enabled during `candles:build` task
- Remove `force` param for `grunt` - allow travis to fail on errors
- Adjust candles to modifications in Poloniex API
- Improve candles performance - get trades once, then generate candles for all periods
- Allow dynamic timeframe for build candles for Poloniex
Closes https://github.com/LiskHQ/lisk-explorer/issues/167
Closes https://github.com/LiskHQ/lisk-explorer/issues/175
> Fix tests, fix candles:build, improve candles performance

- src/app/app.js
The position of `CSS` styles was different compared with the `master` branch. This overload some styles. Fixed by change position of `CSS` modules in `app.js`
Close #207
> Fix css module require position - Closes #207

- .eslintrc
- Gruntfile.js
- lib/api/accounts.js
- lib/api/blocks.js
- lib/api/candles.js
- lib/api/common.js
- lib/api/delegates.js
- lib/api/orders.js
- lib/api/statistics.js
- lib/api/transactions.js
- lib/candles/abstract.js
- lib/candles/bittrex.js
- lib/candles/index.js
- lib/candles/poloniex.js
- lib/orders/abstract.js
- lib/orders/bittrex.js
- lib/orders/index.js
- lib/orders/poloniex.js
- package.json
- webpack.config.js
To keeps the changes small and possible to review, changes in this PR only aims to fix `eslint` errors in `libs` directory. to achieve this, I've enabled eslint before build and I've configured it to run only on `libs` directory. In future PRs, I'll add other directories one by one as I fix issues there.
Closes #262
> Eslint fixings in libs directory - Closes #262

- api/delegates.js
- app.js
- lib/api/delegates.js
- test/api/accounts.js
- test/api/blocks.js
- test/api/common.js
- test/api/delegates.js
- test/api/exchanges.js
- test/api/statistics.js
- test/api/transactions.js
- Updates the Lisk core URLs used in Explorer
- Removes `delegates/getDelegateProposals` endpoint
- Adapts tests accordingly
- Applies some code cleanups
Closes #289
> Update Api/delegates endpoints - Closes #289

- Jenkinsfile.mock
- features/activityGraph.feature
- features/address.feature
- features/block.feature
- features/delegate.feature
- features/delegateMonitor.feature
- features/footer.feature
- features/home.feature
- features/marketWatcher.feature
- features/menu.feature
- features/networkMonitor.feature
- features/tools.feature
- features/topAccounts.feature
- features/transaction.feature
- test/config.test
- Sets up the Jenkins config to run Explorer against mock Api
- Skips all e2e tests, we'll re-enable them one by one with relative tickets from the list of migration tickets
Closes #295
> add Jenkins.mock so tests can be set to run against lisk-mock - Closes #295

- lib/api/common.js
**What we currently have:**
We are making Api calls in this sequence:
`searchHeight`, `searchBlock`, `searchTransaction`, `searchPublicKey`, `searchAccount`, `searchDelegates`
Meaning that to get the results of a search for delegate username, we had to make 6 Api calls.
**What I do here:**
I use the following regex statements
- `/^[0-9]{2,21}[L|l]$/g` for address
- `/^[0-9a-f]{64}$/g` for publicKey
- `/[a-z!@$&_.]/g` which covers pretty much all the delegates
and if all these cases fails, it will make these requests:
`searchHeight`, `searchBlock`, `searchTransaction`, `searchDelegates`.
Since it's possible to choose a number as username, I've put `searchDelegate` here, but since practically all the existing usernames include at least one character, I've put the `searchDelegate` last Api …
> Search performance improvement - Closes #320

- lib/api/candles.js
- lib/api/common.js
*What was the problem?*
I was using `/g` global flag in my regexps to make sure they'll pass even if we have extra white spaces. but it caused my tests to fail in random.
*How did I fix it?*
Removed the global flag. I've added some extra fixings in this endpoint.
*How to test?*
Make sure it:
- Resolves #337 
- Passes all existing tests
- Follows Eslint rules
> Fix an issue with PK Regexp in search Api - Closes #337

- lib/api/blocks.js
- lib/api/common.js
- lib/api/delegates.js
- lib/api/statistics.js
- lib/api/transactions.js
- sockets/activityGraph.js
- sockets/delegateMonitor.js
- sockets/header.js
- sockets/networkMonitor.js
We had inconsistent Api definitions, some had:
`Service.method = (error, success) => {}`
and some had:
`Service.method = (param, error, success) => {}`
and some had:
`Service.method = (error, success, param) => {}`
and this caused confusion when trying to used different Apis in different places.
I used 
`Service.method = (param, error, success) => {}`
everywhere, and where ever the Api didn't need a parameter, I passed `'preserved'` to maintain the sequence of parameters.
Check if there's no regressions in term of the data returned to all the pages.
- The PR solves #360 
> Consistent api params - Closes #360

- src/components/address/address.html
- src/components/market-watcher/market-watcher.service.js
For uninitialised address (Addresses with no public key registered) we don't show the publicKey info, which can be confusing.
Instead of removing the whole row, I mark as `Not initialized`.
Navigate to [16703865346049622043L](https://testnet-explorer.lisk.io/address/16703865346049622043L) in testnet
- The PR solves #372 
> Flag uninitialized addresses - Closes #372

- lib/candles/abstract.js
Log messages are cut, only the first part of the message is visible.
I've changed ``logger(a, b, c)`` notation to ES6-compliant: ``logger(`{$a} ${b} ${c}`)``.
Run the application and compare log file with messages in the code.
The tests are running properly only when changes from #368 are merged.
- The PR solves #376 
> Messages are written to the log properly - Closes #376

- lib/api/candles.js
When data from Redis were not accessible, the application raised an unhandled exception and closed 
I've added additional checks, ensuring that the data are already there.
``redis-cli -p 6380 --raw FLUSHALL``
Run the process on empty Redis database with enabled Market Watcher.
The process should not be stopped.
- The PR solves #377
> getStatistics returns error response instead of raising an exception when no data available in Redis - Closes #377

- lib/candles/abstract.js
- lib/candles/bittrex.js
- lib/candles/poloniex.js
- test/api/exchanges.js
The candlestick charts for the Bittrex exchange were not shown correctly. The backend part of the application that is responsible for this was missing the crucial data, that were not able to be gathered from the original data source - Bittrex API version 1.1.
I switched to the version 2.0 of the Bittrex exchange API.
The new data provided by the API are candlestick data itself, with an interval of 5 mins.
Other charts, such as hour and day charts are generated from the same data source.
I've copied a lot of the original code from the abstract.js file. Most of the code was reused, excluding the grouping part - these functions are performing different operations, based on the data provided in the version 2.0 of Bittrex API.
There is also significant overuse of the Underscore library - I've …
> Fix market watcher candles endpoints - Closes #368

- src/components/activity-graph/activity-graph.html
Buttons on the activity graph did not work correctly.
The reference of the proper function in the template was missing the scope. I've changed it to refer the correct scope.
Open the Activity Graph and click on a node.
- The PR solves #379
> Fix for activity graph buttons - Closes #379

- src/components/market-watcher/market-watcher.html
Described in #387 
I've modified a template, so the data are displayed when available (for Poloniex), but for Bittrex there is only displayed "n/a".
Run the app with candles rebuilt (``grunt candles:build``). The data should be present in the num trades field or the "n/a" is visible.
- The PR solves #387 
> Number of trades placeholder when data unavailable - Closes #387

- Jenkinsfile
The e2e test phase behavior on Jenkins server is unstable.
Same tests work properly on a local MacOS machine.
The problem is still waiting for a proper solution.
We disable the whole e2e test phase temporarily.
Run tests on Jenkins, they sholud pass now.
- The PR solves #394
> Disable E2E tests in Jenkinsfile - Refers #394

- app.js
Redis cache TTL was not set, which results in TTL = inifinte.
I've rewritten the redis SET command wrapper.
Previous solution required two Redis request, the current one - only one.
TTL = 20 s, ex. the market watcher data should be refreshed.
- The PR solves #412
> Redis cache TTL bug fix, reduces DB save to one request - Closes #412

- Dockerfile
- README.md
The market watcher candlestick data needs to be build on the target server, not a build server.
The docker deployment procedure skips the candlestick data build from now on.
Also, updates to the lisk-ansible project have to be done accordingly.
1. Deploy a docker container with the lisk-explorer.
2. Check if the candlesticks are shown correctly.
- The PR solves #411 
> Docker deployment fix - Closes #411

- lib/candles/abstract.js
- lib/candles/bittrex.js
Candlestick data is stored in Redis. The Old Bittrex API allowed to get partial updates and append them to current dataset. The new API provides all data at once in the candlestick format. That caused the data being appended to the old list and there was no way to distinguish already available objects from new ones. In effect, there were multiple copies of identical objects.  
Current implementation contains custom update method for Bittrex API. The old data are always removed before the new data is stored in Redis.
Make sure that:
1. The candlestick view looks ok.
2. The server memory usage is not exceeded. 
- The PR solves #416
> Redis cache fix for Bittrex - Closes #416

- lib/candles/bittrex.js
There was a problem with BTC volume for Bittrex exchange displayed in the statistics section.
I've updated the function responsible for BTC Volume count. 
Market Watcher -> Bittrex tab
- The PR solves #420
> Bittrex BTC volume bug - Closes #420

- lib/api/delegates.js
Due to lisk-core error, some data about delegates cannot be found by the lisk-core api.
That breaks the whole procedure of getting data, which results in missing data in the Delegate Monitor.
I've added one check that makes the whole procedure proceed even if some delegate data are missing.
The problem occurs only when lisk-core is running with the specific set of data.
There is a Postgres dump available that includes missing delegates.
- The PR solves #446 
> Missing delegate data WebSocket fix - Closes #446

- lib/candles/abstract.js
- lib/candles/bittrex.js
- test/api/common.js
The Market Watcher candles for Poloniex are built based on transaction data. Sometimes there are no transactions for a given period of time, in that (rare) case a gap between two candles can be visible. 
I've created a separate function that looks for gaps in the data and fills it with candle objects accordingly.
Go to the Market Watcher page, there should be no gaps visible.
UPDATE: That's the tricky part. Typically there are enough data for all candles to build. This error occurs rarely and only during the update procedure. It is never observed after a rebuild from scratch, but it may occur then as well.
- The PR solves #425
> Gaps between candles fix - Closes #425

- lib/api/statistics.js
- sockets/networkMonitor.js
The number of connected peers displayed random values. The problem was caused on the backend side.
I've found a bug in asynchronous function calls. The backend requests peers list and then combines it with FreeGeoIP results. The former solution didn't wait for the results and sent incomplete data after the last response from Lisk Core. At the time only small part of data was written to the peers list. The solution was to make sure that all peers are checked against the FreeGeoIP service before a response is sent.
Open Network Monitor and check connected peers.
- The PR solves #445 
> Display connected peers count correctly - Closes #445

- lib/api/blocks.js
- test/api/blocks.js
The pagination buttons on blocks page was inverted
I've fixed the pagination logic and added extra tests
Go to /blocks page and test the pagination
- The PR solves #466
> Fix blocks page pagination - Closes #466

- src/components/network-monitor/network-monitor.html
Peers status and OS icons where not visible.
A class name was dropped by #469
OS icon and status should be visible in peers list in network monitor page.
- The PR solves #494 
> Fix a minor css regression

- lib/api/statistics.js
The `/api/statistics/getPeers` response format was not compatible with the Explorer frontend.
I wrote the mapper that ensures correct JSON output format.
Run tests on test blockchain with multiple nodes.
- The PR solves #497 
> Add mapper for statistics/getPeers - Closes #497

- lib/api/statistics.js
Small update to the peers list Jenkins problem.
Since v1.0.0 some hosts do not provide httpPort param.
Using wsPoprt property makes sense because all nodes use WebSockets for this purpose since 1.0.0.
> Peers mapper update - Solves #497

- lib/api/blocks.js
The block height on top bar was showing the node height and not the network height
I've added a mapping function to map the new api response
Check if the block height on top bar is the highest block.
- The PR solves #472
> Fix block height on top bar - Closes #472

- lib/api/statistics.js
Geolocation data was not visible in the Network Monitor peers table.
I've added `location` field in the mapping definition. 
Open the Network Monitor
- The PR solves #517
> Geolocation data included in the Network Monitor socket response - Closes #517

- sockets/delegateMonitor.js
Application crashes when there is no previous block generated by an active delegate
Added a check before assigning the variables
Run the application with less than 100 blocks generated
- The PR solves #529 
> Check if delegate last block is present - Closes #529

- lib/api/delegates.js
The url for delegates on Latest Votes list on Delegate Monitor was pointing to 'undefined'
Applied the delegatesMapper function to core response
Access /delegateMonitor
You should be able to click on a delegate on Latest Votes list and navigate to its page
- The PR solves #528 
> Fix delegate url on delegagte monitor page

- lib/api/statistics.js
The built-in dns module raised an unhandled exception in case of invalid IP address.
The failing code is wrapped around a try-catch block. Due to non-critical importance of this issue, we handle all reverse DNS problems same way - by returning a hostname in the following format: `nnn.nnn.nnn.nnn.unknown'.
There is no clear way to reproduce the bug. The problem should not exist anymore on the alpha- and betanet.
- The PR solves #540
> Invalid reverse dns fix - Closes #540

- lib/api/delegates.js
Latest votes list wasn't showing delegate username
I've removed premature callback call
Access `/delegateMonitor`. You should always see the delegate username when the voter is a delegate
- The PR solves #544 
> Fix latest votes list not showing username - Closes #544

- lib/api/statistics.js
Some block attributes was string when it should be number
Casting those attributes to number
Access `/networkMonitor` and check Best Block section.
The amount should match the Total Amount plus the Total Fee for that block
- The PR solves #547 
> Network Monitor: Incorrect best block amount - Closes #547

- lib/api/blocks.js
The latest blocks list on the home page wasn't showing the delegate username
I've fixed the block mapping function which was assigning the wrong value to delegate attribute
Access the home page and check the "Generated by" column on Latest Blocks list. You should see the delegate username on it.
- The PR solves #555 
> Latest Blocks list not showing username - Closes #555

- src/components/network-monitor/network-monitor.service.js
- src/services/order-by.js
- src/shared/peers/peers.html
Explained in #449 
We had a sort function applies to find the most recent versions, I used the same sort function to order the entire peers list and bound it to view.
- The PR solves #449 
> Order peers list based on version number - Closes #449

- src/components/top-accounts/top-accounts.html
- src/filters/currency.js
- src/filters/middle-ellipsis.js
- Open up space for supplies in top account page in mobile.
- created the middleEllipsis filter to hide a part of LiskIDs.
- modified the currency filter to only show up to 2 floating digits for top accounts.
- The PR solves #537 
> Show supply percentage in top accounts page in mobile - Subtask #537

- lib/api/candles.js
The exchange response doesn't set numTrades attribute when there is no trade and it causes parseInt to return NaN
I set numTrades equal to 0 when NaN
Access `/marketWatcher`. You should see the Num of Trades
- The PR solves #569 
> Fix number of trades - Closes #569

- lib/api/statistics.js
- test/api/statistics.js
Duplicated peers being listed on Network Monitor
I've added `sort` option to peers query in order to make the response consistent.
Additionally I've added a check before processing the peer array.
A test was added to cater for this scenario.
Run `npm run test`
- The PR solves #594
> Duplicated peers fix - Closes #594

- src/components/transactions/transactions.html
Additional data for transactions type 0 not showing on transaction page
Added a new row on Summary table of transaction page
Connect Explorer to betanet and access `/tx/15429910859603286865`
- The PR solves #577 
> Add additional data to transaction page - Closes #577

- api/index.js
- app.js
- lib/api/common.js
- src/app/run.js
- src/filters/epoch-stamp.js
Genesis epoch was hard-coded to mainnet value
I've created an api endpoint to return core constants and use it on epochStamp angular filter
Change the `epochTime` attribute on `helpers/constants.js` core codebase, reload the application and check any transaction timestamp displayed on explorer
- The PR solves #534 
> Use core epoch - Closes #534

- known.json
known.json needed an update to identify 16293716040102736949L
added the entry for 16293716040102736949L
- The PR solves #588
> Add new coincheck wallet to known.json - Closes #588

- src/components/header/header.css
Opacity in network status bar 
Used `rgb` rather than `rgba` style
Scroll the page and check the network status bar
- The PR solves #637 
> Remove opacity network bar - Closes #637

- src/components/currency-selector/currency-selector.directive.js
Currency dropdown not closing after selected on mobile view
Actively setting `isCollapsed` to true when changing currencies
Access the application on mobile view and change currencies
- The PR solves #649 
> Always close currency dropdown after selecting - Closes #649

- features/menu.feature
- src/components/header/header.css
- src/components/header/header.html
- src/components/search/search.directive.js
- src/components/search/search.html
User required two clicks to perform a serch
As discussed with the team, I changed the behaviour to display the search input when there is enough space for it (when not on mobile view)
Check the search bar on desktop and mobile views
- The PR solves #596
> Show search input when not on mobile - Closes #596

- src/assets/styles/common.css
- src/components/address/address.html
- src/directives/clip-copy.js
- src/shared/transaction-item/transaction-item.html
Unexpected horizontal scrollbar on Address page when on mobile view due `tooltip` element
I've changed the tooltip position and added `padding` to the right of the table
Access Address page on mobile view
- The PR solves #670 
> Change tooltip position avoiding undesired margins - Closes #670

- src/components/header/header.css
- src/components/search/search.directive.js
- src/components/search/search.html
To search in mobile devices, we need to click on the search icon and then click on search input to focus onto.  while it should be possible with a single click.
Tweaked the directive to automatically focus after the input expanded.
- The PR solves #669 
>  Automatically focus on searchbox after expanding - Closes #669

- features/networkMonitor.feature
- src/components/network-monitor/network-monitor.html
- src/components/network-monitor/network-monitor.service.js
Disconnected peers not showing on Network Monitor
Added disconnected peers list back
Check `/networkMonitor`
- The PR solves #623
> List disconnected peers on Network Monitor - Closes #623

- lib/api/statistics.js
- src/shared/peers/peers.html
- test/api/statistics.js
Port column on Network Monitor page was listing WS Port only
I've added both HTTP Port and WS Port on the list
Check `/networkMonitor`
- The PR solves #700 
> Show both HTTP and WS ports on Network Monitor - Closes #700

- src/components/network-monitor/network-monitor.service.js
The page won't scroll when mouse/touch was positioned over the map area
I've disabled `dragging`, `scrollWheelZoom` and `tap` options on leaflet library
Access `/networkMonitor` on desktop and mobile version and scrolls the page up and down over the map area
- The PR solves #694 #693 
> Make map area scrollable on mouse/touch dragging - Closes #694 #693

- features/address.feature
- features/menu.feature
- lib/api/transactions.js
- src/components/address/address.html
Use of `forEach` on multi requests which leads to premature callback call.
Replaced `forEach` for `async.parallel`
`npm run e2e-test -s`
- The PR solves #652 
> Make sure all transactions are returned on multi requests - Closes #652

- redis.js
Disconnected Redis caused backend crash.
The Redis client tries to reconnect after a connection with Redis server is lost.
Run the process and try to stop and restart Redis server.
- The PR solves #696
> Restore redis connection - Closes #696

- Jenkinsfile
- features/step_definitions/generic.step.js
- package.json
E2E tests were skipped due unstability
I've re-introduced e2e tests and added xvfb plugin to jenkins
Make sure the jenkins checks on this PR are green ;)
- The PR solves #394 
> Re-introduce e2e tests on jenkins - Closes #394

- lib/api/accounts.js
- lib/api/transactions.js
- test/api/accounts.js
- test/api/transactions.js
- utils/core.js
Some inputs are not properly parsed by the frontend client. It results with an empty transaction table on the account page. 
The address input is always parsed against common issues: lowercase `L` and white characters.
This ensures that the core backend always receives an address in the following format: `12345L`.
Visit the `91540L` page, transactions should be visible.
- The PR solves #712
> Bug - empty transaction list - Closes #712

- features/step_definitions/generic.step.js
Unstable E2E tests on Jenkins
Increased timeout in order to wait more for response before test crash
`npm run e2e`
- The PR solves #460 
> Increase e2e tests timeout - Closes #460

- package-lock.json
- src/app/app.js
- src/assets/styles/common.css
- src/components/currency-selector/currency-selector.directive.js
- src/components/currency-selector/currency-selector.html
- src/components/header/header.html
- src/components/navigation-dropdown/index.js
- src/components/navigation-dropdown/navigation-dropdown.directive.js
- src/components/navigation-dropdown/navigation-dropdown.html
- src/components/navigation-dropdown/navigation-dropdown.module.js
- src/components/rounding-selector/index.js
- src/components/rounding-selector/rounding-selector.directive.js
- src/components/rounding-selector/rounding-selector.html
- src/components/rounding-selector/rounding-selector.module.js
- src/filters/currency-code-to-name.js
- src/filters/index.js
The increased number of supported currencies raised a need for making the currency picker more readable.
The currency list was split into three categories: popular/international, European and Asian currencies.
Run the application, the updated currency picker should be visible.
- The PR solves #721 
> Currency picker redesign - Closes #721

- api/index.js
- api/newsfeed.js
- lib/api/newsfeed.js
- package.json
- services/index.js
- services/newsfeed/TwitterService.js
- services/newsfeed/index.js
- test/api/newsfeed.js
- test/index.js
Implementation for LiskHQ Twitter Newsfeed.
API Endpoint:
`/api/newsFeed`
params:
`source` -> all | twitter (default: all)
`limit` -> integer (default: 20)
response: 
```
[
{
source: String, 
sourceId: String  // that'd be a Twitter id if available, otherwise null
timestamp: Integer, 
content: String, 
url: String
},
]
```
- The PR solves #714 
>  Implement Newsfeed Service for Twitter - Closes #714

- src/components/transactions/transactions.html
- src/services/tx-types.js
Asset data from transactions not being displayed on Transaction page
New section added on Transaction page
Connecting to Testnet and accessing the following transactions:
Type 0: `/tx/5072002836908163001`
Type 1: `/tx/3320243316616300582`
Type 2: `/tx/17769273069468847453`
Type 3: `/tx/15602595912374724830`
Type 4: `/tx/8191213966308378713`
Type 5: `/tx/14602496231523117483`
Type 6: `/tx/13847108354832975754` (this is not showing due an core issue https://github.com/LiskHQ/lisk/issues/2194)
Type 7: `/tx/7297225435992500205`
* The PR solves #747
* Tests pass
> Display transaction asset data on Transaction page - Closes #747

- src/components/home/home.component.js
- src/components/home/home.html
Angular directive `accountHref` is not re-triggered when transactions list is updated keeping the Sender/Recipient links the same as the initial loaded.
Setting the `href` attribute when the transactions list is received
Access the home page and wait for a new transaction to show up.
Sender/Recipient links should navigate to the correct page.
* The PR solves #763 
* Tests pass
> Fix broken links when txs list updates - Closes #763

- services/newsfeed/TwitterService.js
The Explorer process crashed when the `/api/newsfeed` was accessed and one of tweets didn't contain an URL.
An additional security check is done before the potential data are accessed.
Test the `/api/newsfeed` route, the process should not crash.
* The PR solves #787
* Tests pass
> Add safety check during Twitter response URL parse

- Jenkinsfile
Add cache functions from jenkins library to speed up builds
Adding cache in the `npm install` step
In Jenkins 
https://jenkins.lisk.io/job/lisk-explorer/job/use_jenkins_cache/
> Use jenkins cache

- api/accounts.js
- features/delegate.feature
- lib/api/accounts.js
- src/components/address/address.component.js
- src/components/delegate/delegate.component.js
- src/components/delegate/delegate.html
- test/api/accounts.js
Address page takes ages to load when the address is a delegate and have too many voters
The `Load more...` functionality was added to the voters list
Access `/address/17621212458226596154L` connected to a mainnet node.
* The PR solves #803 
* Tests pass
> Add 'load more' functionality to voters list - Closes #803

- app.js
After implementation of `Google Tag Manager` the console intermittently shows a `img-src` CSP violation. It happens because GTM loads some assets onto the page to keep track of it and for some reason the source of these assets can change based on the location where the page is accessed.
As the list of possibles domains for google is very long (google.com, google.de, google.co.uk, etc..) to be whitelisted, I've expanded the `img-src` policy to any secure source (**https**).
In addition, I've restricted the `script-src` by removing the `unsafe-inline` and adding the inline script hash instead.
Load the page and check the console.
* The PR solves #808 
* Tests pass
* Commit messages follow …
> Content security policy issue - Closes #808

- lib/api/common.js
Search bar not returning one digit address
Updated the regular expression that validates addresses
Search for `0L`
* The PR solves #687 
* Tests pass
> Allow searching for one digit address - Closes #687

- src/app/app.js
- src/components/cookies-banner/cookies-banner.directive.js
Cookie expire date for the cookie banner was not working.
- set expireDate to 2 years ahead on cookie-banner.directive.js
- you can test it on console by removing the cookie and recreate the cookie
* The PR solves #841 
* Tests pass
>  Configure cookie expiry date - Closes #841

- src/assets/styles/common.css
- src/components/home/home.html
The current spacings do not look well on the desktop view.
At the landing page, the padding-bottom for the .big-info element is not needed there and should be reduced to 0.
Added a new class .top-pb at parent divs of .big-info on home.html, and set the value of padding-bottom 0px.
Checked on the browser.
* The PR solves #852 
* Tests pass
> Adjust Spacing on big-info elements 2 - Closes #852 

- src/components/transactions/transactions.component.js
- src/services/pagination.js
- src/shared/transactions-list/transactions-list.html
Pagination buttons were not working correctly.
The AngularJS ui-router was configured to watch the URL.
Go to the transaction page and use pagination or change the URL manually.
* The PR solves #850
* Tests pass
> Pagination logic update - #850

- src/assets/styles/common.css
- src/components/bread-crumb/bread-crumb.html
- src/components/currency-selector/currency-selector.html
- src/components/rounding-selector/rounding-selector.directive.js
- src/components/rounding-selector/rounding-selector.html
The currency selector didn't work due to the namespace collision.
Two different namespaces are used for the currency selector (`cs`) and for the rounding selector (`rs`). There are also few UI fixes included.
Decimal places and currency should be able to set.
* The PR solves #849
* Tests pass
> Currency picker fix - #849

- src/assets/styles/common.css
- src/components/header/header.css
The logo and the pull-down menu at right were not aligned to the container below.
Changed the paddings.
Checked on the browser.
* Tests pass
> Align logo and nav bar to the container - Closes #859

- src/assets/styles/common.css
- src/components/blocks/blocks.html
- src/services/pagination.js
- src/shared/transactions-list/transactions-list.html
There was no indicator for the current page at the transactions section for an account.
Added the page indicator.
Checked on the browser.
* The PR solves #858 
* Tests pass
> Add a page indicator to account page - Closes #858

- utils/candles.js
- utils/exchange-api/index.js
- utils/orders.js
Some info messages were logged as error.
The log levels are assigned correctly.
Run the Explorer backend and check the messages.
* The PR solves #870
* Tests pass
> Log levels update - Closes #870

- src/components/transactions/transactions.component.js
- It showed negative numbers on the pagination at Transaction when the transactions had only 1 page.
- Add a filter to a pagination function and made it show only positive numbers.
- Checked on the browser.
* Tests pass
> Show only positive numbers for the transaction pagination - #859

- config.js
- package-lock.json
- package.json
- utils/knownAddresses.js
The content of the `known.json` file differs depending on the network and is independent of the Explorer release cycle.
The `known.json` file is stored on S3 servers and can be updated independently of changes done to the Explorer codebase. In case the S3-based data are not available the local version stored in the codebase will be used.
Adjust config.json accordingly and run the application. On Mainnet, there should be visible correct names in `Top Accounts`.
* The PR solves #601
* Tests pass
> Add HTTP-based known.json source - Closes #601

- Dockerfile
- Removed bower and nasm
- Use of COPY with --chown argument
- Use npm ci instead of npm install
- Added stage to install dependencies before copy source code, so the
layer with deps can be cached.
* The PR solves #889 
* Tests pass
> Improvements on Dockerfile - Closes #889

- src/components/transactions/transaction.html
- The text included in the transaction type 0 in Transaction details may cover the label.
- Removed unnecessary class.
- Checked on Chrome.
* The PR solves #892 
* Tests pass
> Modify text alignment for Transaction type 0 - Closes #892

- lib/api/delegates.js
The data type of amount and fee that are created in the transaction mapper in the delegates API are string while they are number in the transactions API. They should be aligned.
Added Number() function at amount and fee in the transaction mapper.
Run grunt test and e2e test.
* The PR solves #894 
* Tests pass
> Align response data of Delegates API - Closes #894

- api/common.js
- features/menu.feature
- lib/api/common.js
- lib/api/delegates.js
- src/components/search/search.directive.js
- src/components/search/search.html
- test/api/common.js
The search results didn't show all entries matching query based on the blockchain data source.
- Normalized the response format.
- Added strict search and full-text search as two separate complementary methods producing one result.
- Updated the frontend code to support the new response format.
- Added proper transaction ID, block ID and block height handling.
Try to search for `9` or `genesis` on testnet.
* The PR solves #898
* Tests pass
> Search improvements - Closes #898

- src/assets/styles/common.css
- src/components/address/address.component.js
- src/components/address/address.html
The transaction list filtering buttons was not available.
The following filter presets were added: Show all Transfers Sent Received Voting
Go to the account page and click the buttons.
* The PR solves #901
* Tests pass
> Add filter presets - Closes #901

- app.js
- lib/api/transactions.js
Due to the API change, the unconfirmed transactions are not displayed on the landing page.
The `getUnconfirmedTransactions` controller uses the SDK 2.0 API to get transactions in the state `ready`.
Run the Explorer and open the landing page.
* The PR solves #911
* Tests pass
> SDK 2.0 support - Closes #911

- features/breadcrumb.feature
- package-lock.json
- package.json
There were about 300 vulnerabilities.
```
found 332 vulnerabilities (8 low, 18 moderate, 306 high) in 20303 scanned packages
run `npm audit fix` to fix 314 of them.
13 vulnerabilities require semver-major dependency updates.
5 vulnerabilities require manual review. See the full report for details.
```
I did `npm audit fix`
Run the regular test suite
* Tests pass
> Update outdated dependencies

- src/components/footer/footer.html
LiskUSA's Booster Club was able to add 17 Boosting Members to our Discord.
As a result we get a Static "Vanity" Address http://discord.gg/lisk
> Amend new static Discord Link

- docker/explorer/docker-compose.yml
- docs/run_with_docker.md
- lib/api/statistics.js
- utils/knownAddresses.js
Changes described in #931 had to be made
Note that peers locations (flags and map) are currently missing because of freegeoip not being available anymore. This is not related to core 3.0 migration and will be solved separately.
Follow steps to reproduce in #931
* The PR resolves #931
* Tests pass
> Update to Core 3.0.0-alpha.1 API changes - Closes #931

- app.js
- benchmark.js
- config.js
- docker/explorer/.env
- docker/explorer/docker-compose.yml
- docker/jenkins/.env
- package-lock.json
- package.json
- src/filters/net-hash.js
The betanet nethash to network name translation was missing.
- Added the network name with a proper nethash
- Added support for HTTPS/WSS
`npm test`
* The PR solves #934
* Tests pass
> Nethash to network name translation - Closes #934
